(function(){
const R=[];const T=(k,f)=>{try{const v=f();R.push((v?"PASS ":"FAIL ")+k)}catch(e){R.push("FAIL "+k+" <- 오류: "+e.message)}};
const submit=f=>f.dispatchEvent(new Event("submit",{cancelable:true,bubbles:true})),q1=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const PUB=["home","business","events","news","map","voice","notice","gallery","clips","docs","login","about-greeting","about-history","about-ci","about-rules","about-org","about-map","support","support-hope","support-amb","support-status","free","links","admin-c","membersearch","myedit","join","search"];
const valid=h=>PUB.includes(h)||h==="main"||(h.startsWith("room-")&&br(h.slice(5)))||(h.startsWith("m-")&&MROUTES[h])||(h.startsWith("c-")&&CROUTES[h]);
const links=()=>qa("a[href^='#']").map(a=>a.getAttribute("href").slice(1)).filter(h=>h!=="main"&&h!=="");
SESS=null;
T("공개 화면 링크 전수 검사",()=>{let n=0,bad=[];[...PUB,...BR.map(b=>"room-"+b.id)].forEach(r=>{go(r);links().forEach(h=>{n++;if(!valid(h))bad.push(r+">"+h)})});R.push("  (링크 "+n+"개 검사, 잘못 "+bad.length+(bad.length?": "+bad.slice(0,4).join(","):"")+")");return bad.length===0&&n>1500});
T("공개 화면 실제 클릭 이동",()=>{let n=0,fail=[];PUB.forEach(r=>{go(r);const c=links().length;for(let i=0;i<c;i++){go(r);const a=qa("a[href^='#']").filter(a=>a.getAttribute("href")!=="#main")[i],h=a.getAttribute("href").slice(1);a.click();n++;if(cur!==h)fail.push(r+">"+h+"("+cur+")")}});R.push("  (클릭 "+n+"회, 실패 "+fail.length+(fail.length?": "+fail.slice(0,4).join(","):"")+")");return fail.length===0&&n>1000});
[[0,MNAV_B],[1,MNAV_B],[2,MNAV_R],[3,MNAV_C]].forEach(([i,nav])=>T("관리 화면 이동·링크: "+ACCT[i].title+" ("+nav.length+"개 메뉴)",()=>{SESS=ACCT[i];let bad=[];nav.forEach(x=>{go(x[0]);if(cur!==x[0])bad.push("이동실패:"+x[0]);if(!q1(".side"))bad.push("메뉴없음:"+x[0]);links().forEach(h=>{if(!valid(h))bad.push("링크:"+x[0]+">"+h)})});return bad.length===0}));
SESS=null;go("home");
T("홈: 배너 3장, 다음 버튼으로 전환",()=>{if(qa(".slide").length!==3)return false;q1('[data-act="slide"][data-d="1"]').click();return qa(".slide")[1].classList.contains("on")&&qa(".dots button")[1].getAttribute("aria-current")==="true"});
T("홈: 빠른 메뉴 6개·숫자 띠 4칸",()=>qa(".quick a").length===6&&qa(".stat>div").length===4);
T("홈: 구역 순서(공지→뉴스→갤러리→NEW)",()=>{const h=qa(".sech h2").map(x=>x.textContent.trim());return h[0].startsWith("공지사항")&&h[1].startsWith("최신복지뉴스")&&h[2].startsWith("포토갤러리")&&h.length===5});
T("홈: 달력·협력기관 4곳·포스터·왼쪽 로그인·세로 메뉴 6개",()=>!!q1("#cal .calg")&&qa(".coops a").length===4&&!!q1(".poster img")&&!!q1(".lbox.login")&&qa(".vmenu .g").length===6);
T("빠른 이동: Ctrl+K로 열고 '성남' 입력 후 Enter → 성남지부 방",()=>{document.dispatchEvent(new KeyboardEvent("keydown",{key:"k",ctrlKey:true,bubbles:true}));if(!q1("#cmdk").classList.contains("open"))return false;const i=q1("#cmdq");i.value="성남";i.dispatchEvent(new Event("input",{bubbles:true}));i.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}));return cur==="room-seongnam"&&!q1("#cmdk").classList.contains("open")});
T("빠른 이동: Esc로 닫힘",()=>{document.dispatchEvent(new KeyboardEvent("keydown",{key:"k",metaKey:true,bubbles:true}));const o=q1("#cmdk").classList.contains("open");document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}));return o&&!q1("#cmdk").classList.contains("open")});
/* 지부장 */
SESS=ACCT[0];go("m-dash");
T("알림 종: 안 읽은 알림 표시 → 열기 → 모두 읽음",()=>{const n=q1(".bell .n");if(!n||+n.textContent<1)return false;q1('[data-act="bell"]').click();if(q1("#bellpop").hidden||qa("#bellpop li").length<1)return false;q1('[data-act="readall"]').click();return !q1(".bell .n")});
T("알림 종: 항목을 누르면 해당 화면으로 이동",()=>{pushNotif("branch","시험 알림","이동 시험",{bid:"seongnam",go:"m-events"});go("m-dash");q1('[data-act="bell"]').click();q1('#bellpop li[data-act="readn"]').click();return cur==="m-events"});
go("m-members");
T("회원 목록: 빠른 선택 4개, '회비 미납' 누르면 미납만 표시",()=>{if(qa(".pillbar [data-act='seg']").length!==4)return false;q1('[data-act="seg"][data-k="unpaid"]').click();const rows=qa("#mtab tbody tr");return rows.length>0&&rows.every(r=>r.textContent.includes("미납"))});
T("회원 안내 보내기: 확인창 → 발송 기록",()=>{q1('[data-act="seg-send"]').click();if(!q1("#modal").classList.contains("open"))return false;q1('[data-act="mok"]').click();return AUDIT.some(a=>a.a.startsWith("회원 안내 발송"))});
T("회원 목록: 전체 보기로 되돌리기",()=>{q1('[data-act="seg"][data-k="all"]').click();return qa("#mtab tbody tr").length===10});
go("m-inq");
T("문의함: AI 답변 초안 버튼 → 답변 칸 채워짐",()=>{const b=qa('[data-act="ai-draft"]');if(b.length<2)return false;b[0].click();return qa("textarea")[0].value.includes("안녕하세요")});
go("m-report");
T("월간 리포트(지부): 요약·권고·복사 버튼",()=>{const t=q1("#rcard").textContent;return t.includes("2026년 10월")&&t.includes("권고")&&!!q1('[data-act="rpt-copy"]')});
T("가입 1차 승인 → 시도회장 알림 생성",()=>{go("m-apps");const n0=NOTIFS.filter(n=>n.aud==="region").length;q1('[data-act="app-ok"]').click();return NOTIFS.filter(n=>n.aud==="region").length===n0+1});
SESS=ACCT[2];go("m-r2");
T("시도 2차 승인 → 중앙 알림 생성",()=>{const n0=NOTIFS.filter(n=>n.aud==="central").length;q1('[data-act="r-ok"]').click();return NOTIFS.filter(n=>n.aud==="central").length===n0+1});
T("시도회장 월간 리포트: 경기복지회",()=>{go("m-report");return q1("#rcard").textContent.includes("경기복지회")});
/* 중앙 사무국 */
SESS=ACCT[3];go("c-dash");
T("전국 현황: 차트 2개·시도 칸 20개·승인 흐름 4단계",()=>qa("svg.chart").length===2&&qa(".heat button").length===20&&qa(".funnel .fr").length===4);
T("전국 현황: 시도 칸을 누르면 조직 관리로 이동(경기 필터)",()=>{q1('.heat [data-sd="경기"]').click();return cur==="c-tree"&&TQ==="경기"});
T("조직 관리: 검색 '성남' → 성남지부만, 지부 누르면 상세 창",()=>{go("c-tree");TQ="";const i=q1("#tq");i.value="성남";i.dispatchEvent(new Event("input",{bubbles:true}));const t=q1("#tree").textContent;if(!t.includes("성남지부")||t.includes("강원복지회"))return false;q1(".leaf").click();return q1("#modal").classList.contains("open")&&q1("#modalbox").textContent.includes("성남지부")});
T("상세 창 닫기",()=>{q1('[data-act="mclose"]').click();return !q1("#modal").classList.contains("open")});
go("c-approve");
T("결재함: 가입 확정 대기 목록에 신청이 보임",()=>qa(".msg").length>=1&&qa('[data-act="c-ok"]').length>=1);
T("가입 확정 → 승인 단계 4, 지부장 알림",()=>{const a=APPS.find(x=>x.stage===3);q1('[data-act="c-ok"]').click();return a.stage===4&&NOTIFS.some(n=>n.t==="가입이 확정되었어요")});
T("결재함: 서류 승인 → 처리 완료",()=>{go("c-approve");q1('[data-act="aptab"][data-k="docs"]').click();const b=q1('[data-act="d-ok"]');if(!b)return false;const i=+b.dataset.i;b.click();return SUBM[i].s==="처리 완료"});
T("결재함: 서류 반려",()=>{go("c-approve");q1('[data-act="aptab"][data-k="docs"]').click();const b=q1('[data-act="d-no"]');if(!b)return true;const i=+b.dataset.i;b.click();return SUBM[i].s==="반려"});
T("결재함: 지부장 교체 승인",()=>{go("c-approve");q1('[data-act="aptab"][data-k="hand"]').click();q1('[data-act="h-ok"]').click();return HAND[0].s===1});
go("c-notice");
T("공지 발송: AI로 다듬기 → 내용 채워짐",()=>{q1("#ntT").value="11월 교육 안내";q1("#ntB").value="11월 12일 온라인 교육이 있습니다.";q1('[data-act="ai-notice"]').click();return q1("#ntB").value.includes("문의는 복지회 사무국")});
T("공지 발송: 경기 대상으로 보내기 → 목록 맨 위·알림·읽음률",()=>{q1("#ntS").value="s:경기";const n0=SENT.length;submit(q1('[data-form="cnotice"]'));return SENT.length===n0+1&&SENT[0].scope==="s:경기"&&NOTIFS.some(n=>n.t==="새 공지: 11월 교육 안내")&&qa(".readbar").length>3});
T("공지 발송: 읽지 않은 곳에 다시 알리기",()=>{const b=q1('[data-act="resend"]');if(!b)return true;b.click();return AUDIT.some(a=>a.a.startsWith("공지 재알림"))});
go("c-rbac");
T("권한 관리: 잠긴 칸 있고, 칸을 누르면 값이 바뀌고 기록 남음",()=>{if(qa(".cellb[disabled]").length<5)return false;const b=q1('.cellb[data-act="rb"]'),f=RB[+b.dataset.f],r=+b.dataset.r,v0=f[1][r];b.click();return f[1][r]!==v0&&AUDIT.some(a=>a.a.startsWith("권한 변경"))});
go("c-auto");
T("자동화 규칙: 6개, 끄면 반영·기록",()=>{if(qa(".rule").length!==6)return false;const c=q1('[data-act="rule"]');c.checked=false;c.dispatchEvent(new Event("change",{bubbles:true}));return AUTO[0].on===false&&AUDIT.some(a=>a.a.startsWith("자동화 규칙 끔"))});
T("자동화 규칙: 오늘 실행 미리보기 창",()=>{q1('[data-act="rule-run"]').click();const o=q1("#modal").classList.contains("open")&&q1("#modalbox").textContent.includes("오늘 실행하면");q1('[data-act="mclose"]').click();return o});
go("c-report");
T("월간 리포트(중앙): 범위를 경기복지회로 바꾸면 다시 작성",()=>{const s=q1("#rsc");s.value="s:경기";s.dispatchEvent(new Event("change",{bubbles:true}));return q1("#rcard").textContent.includes("경기복지회")});
T("월간 리포트: 복사 버튼이 오류 없이 동작",()=>{q1('[data-act="rpt-copy"]').click();return true});
go("c-log");
T("활동 기록: '승인' 필터",()=>{q1('[data-act="logf"][data-k="승인"]').click();const l=qa(".tl li");return l.length>0&&l.every(li=>li.textContent.includes("승인"))});
/* 권한·역할 */
T("권한: 지부장은 중앙 화면에 못 들어감",()=>{SESS=ACCT[0];go("c-dash");return cur==="m-dash"});
T("권한: 시도회장은 중앙 화면에 못 들어감",()=>{SESS=ACCT[2];go("c-approve");return cur==="m-dash"});
T("권한: 중앙이 지부장 화면으로 가면 중앙 현황으로",()=>{SESS=ACCT[3];go("m-members");return cur==="c-dash"});
T("권한: 로그인 없이 중앙 화면 → 로그인",()=>{SESS=null;go("c-tree");return cur==="login"});
T("로그인 화면에 계정 4개, 중앙 계정 선택 → 전국 현황",()=>{go("login");if(qa('[data-act="login"]').length!==4)return false;qa('[data-act="login"]')[3].click();return cur==="c-dash"&&q1(".side .me").textContent.includes("중앙 사무국")});
T("로그아웃 → 홈",()=>{q1('[data-act="logout"]').click();return cur==="home"&&SESS===null});
T("회원가입 → 선택한 지부의 가입 승인함 + 알림",()=>{go("join");q1("#jS").value="경기";q1("#jS").onchange();q1("#jN").value="시험가입";q1("#jP").value="010-1234-5678";q1("#jC").checked=true;const n=APPS.length;submit(q1('[data-form="join"]'));return APPS.length===n+1&&NOTIFS.some(x=>x.bid===JOINED.b&&x.t==="가입 신청이 접수되었어요")});
const pass=R.filter(x=>x.startsWith("PASS")).length,tot=R.filter(x=>/^(PASS|FAIL)/.test(x)).length;
document.body.innerHTML='<pre style="font:17px/1.5 monospace;padding:16px;background:#fff;color:#000;position:fixed;inset:0;z-index:9999;margin:0;overflow:auto;white-space:pre-wrap">'+R.join("\n")+"\n\n결과 "+pass+" / "+tot+"</pre>";
})();
