/* ===== v5d: 전국 현황 화면 균형 정돈 (왼쪽·오른쪽 두 열을 각각 쌓음) ===== */
function cDash(){const tot=BR.reduce((a,b)=>a+b.mem,0),act=BR.filter(b=>pts(b.id)>=90).length,actP=Math.round(act/BR.length*100);
 const pend=APPS.filter(a=>a.stage>=1&&a.stage<=3).length,inqOpen=BR.reduce((a,b)=>a+openInq(b.id),0),evM=EV.filter(e=>e.d.startsWith("2026-10")).length;
 const stg=[["접수",APPS.length],["지부 승인",APPS.filter(a=>a.stage>=2).length],["시·도 승인",APPS.filter(a=>a.stage>=3).length],["중앙 확정",APPS.filter(a=>a.stage>=4).length]],mx=Math.max(1,stg[0][1]);
 const lvl={},cn={};BR.forEach(b=>{lvl[b.s]=Math.max(lvl[b.s]||0,lv(pts(b.id)));cn[b.s]=(cn[b.s]||0)+1});
 let heat="";for(let yy=1;yy<=5;yy++)for(let xx=1;xx<=4;xx++){const t=SIDO.find(z=>z[1]===xx&&z[2]===yy);heat+=t?`<button class="h${lvl[t[0]]||0}" data-act="tree-s" data-sd="${t[0]}" aria-label="${t[0]} 지부 ${cn[t[0]]||0}곳, 활동 ${lvl[t[0]]||0}단계. 눌러서 조직 관리로 이동">${t[0]}<small>${cn[t[0]]?cn[t[0]]+"곳":"준비중"}</small></button>`:`<button class="hx" tabindex="-1" aria-hidden="true"></button>`}
 const warn=BR.map(b=>({b,why:[pts(b.id)<100?"활동 점수 "+pts(b.id)+"점":"",openApps(b.id)>=3?"가입 대기 "+openApps(b.id)+"건":"",openInq(b.id)>=2?"문의 "+openInq(b.id)+"건 대기":""].filter(Boolean)})).filter(x=>x.why.length).sort((a,c)=>pts(a.b.id)-pts(c.b.id)).slice(0,5);
 return shell("c-dash","전국 현황","시·도복지회와 지부의 활동, 승인 흐름, 주의가 필요한 곳을 한눈에 봅니다.",
 `<div class="mk"><a href="#c-tree"><b class="num">${tot.toLocaleString()}</b><span>전체 회원(예시)</span><br><span class="up">▲ 신규 가입 꾸준(예시)</span></a><a href="#c-tree"><b class="num">${actP}%</b><span>활동 중인 지부</span><br><span class="${actP>=60?"up":"dn"}">${act}/${BR.length}곳이 90점 이상</span></a><a href="#c-approve"><b class="num">${pend}</b><span>승인 대기</span><br><span>${APPS.filter(a=>a.stage===3).length}건은 중앙 확정 차례</span></a><a href="#c-log"><b class="num">${evM}</b><span>이번 달 행사</span><br><span>답변 대기 문의 ${inqOpen}건</span></a></div>
 <div class="two"><div class="stack"><div class="card lift"><h3 style="margin-bottom:2px">활동 지부 비율 추이</h3><p class="small mut" style="margin:0 0 8px">지난달까지는 예시 값, 이번 달은 현재 데이터</p>${svgLine(MONTHS,[38,41,45,47,52,58,actP],"%","월별 활동 지부 비율 꺾은선 그래프")}<h3 style="margin:18px 0 2px">월별 가입 신청</h3><p class="small mut" style="margin:0 0 8px">이번 달은 현재 접수 건수</p>${svgBars(MONTHS,[18,22,25,31,29,38,APPS.length],"","월별 가입 신청 막대 그래프")}</div>
 <div class="card lift"><h3 style="margin-bottom:6px">주의가 필요한 지부</h3>${warn.length?`<ul class="list">${warn.map(x=>`<li><span><b>${esc(x.b.nm)}</b> <span class="small mut">${esc(x.b.s)}</span><br><span class="small mut">${x.why.join(" · ")}</span></span><button class="btn sm line" data-act="node" data-id="${x.b.id}">살펴보기</button></li>`).join("")}</ul>`:`<p class="mut" style="margin:0">지금은 주의가 필요한 지부가 없습니다.</p>`}</div></div>
 <div class="stack"><div class="card lift"><h3 style="margin-bottom:10px">시·도별 활동</h3><div class="heat">${heat}</div><div class="legend2"><span><i style="background:var(--brand-soft)"></i>없음</span><span><i style="background:var(--t1)"></i>1</span><span><i style="background:var(--t2)"></i>2</span><span><i style="background:var(--t3)"></i>3</span><span><i style="background:var(--t4)"></i>4단계</span></div></div>
 <div class="card lift"><h3 style="margin-bottom:10px">가입 승인 흐름</h3><div class="funnel">${stg.map(s=>`<div class="fr"><span>${s[0]}</span><div class="fb"><i style="width:${Math.round(s[1]/mx*100)}%"></i></div><b class="num">${s[1]}</b></div>`).join("")}</div><p class="small mut" style="margin:10px 0 0">단계마다 줄어드는 곳이 병목입니다. 3일 넘게 머무는 신청은 자동화 규칙으로 알립니다.</p></div>
 <div class="card lift"><h3 style="margin-bottom:6px">최근 활동 기록</h3>${auditList(5)}</div></div></div>`)}
