/* ===== v6: 30년 발자취·제휴 분석 (코덱스 리아 조사 반영 · 공개 가능한 항목만) ===== */
const B30CATS=["협약·제휴","위탁·운영·고용","후원·나눔","장학·교육","문화·체육·행사"];
const B30TABS=[["개요","biz30"],["사업 유형","biz30-types"],["사례 찾기","biz30-cases"],["지역·연도","biz30-map"],["조사 공백","biz30-gaps"],["자료·방법","biz30-data"]];
let B30F={c:"전체",s:"전체",v:"전체",q:""};
const b30n=()=>B30.length,b30ok=()=>B30.filter(x=>x.verdict==="자료근거 있음").length,b30cnt=c=>B30.filter(x=>x.cat===c).length;
const b30head=cur=>pageHead("30년 발자취·제휴 분석",[["복지회소개"],["30년 발자취·제휴 분석"]])+`<div class="b30tabs" role="navigation" aria-label="30년 분석 구역">${B30TABS.map(t=>`<a href="#${t[1]}" ${t[1]===cur?'aria-current="page"':""}>${t[0]}</a>`).join("")}</div><div class="note w"><b>중간 조사입니다.</b> 공개된 기사와 공문서를 모은 결과이며 전수조사가 아닙니다. 아래 항목 수는 확정된 업무제휴 건수가 아니고, 자료가 없다고 사업이 없었다는 뜻도 아닙니다.</div>`;
const verdictChip=v=>`<span class="chip ${v==="자료근거 있음"?"g":v==="후보"?"o":"m"}">${esc(v)}</span>`;
const srcLink=x=>`<a class="lk" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">출처 보기</a>`;
const caseCard=x=>`<article class="card lift case"><div class="row"><span class="chip">${esc(x.org)}</span>${verdictChip(x.verdict)}</div><h3>${esc(x.party)}</h3><p>${esc(x.what)}</p><p class="small mut">${esc(x.when)} · ${esc(x.type)}</p><p class="caseline">실행 수준: ${esc(x.level)}<br>확인되지 않은 것: ${esc(x.gap)}</p>${srcLink(x)}</article>`;
const catBars=link=>{const mx=Math.max(1,...B30CATS.map(b30cnt));return`<div class="hbar">${B30CATS.map(c=>`<div class="r"><span>${c}</span><div class="t"><i style="width:${Math.round(b30cnt(c)/mx*100)}%"></i></div><b class="num">${b30cnt(c)}</b></div>`).join("")}</div>`};
function vB30(){const feat=["E015","E016","E017","E009","E007","E018"].map(id=>B30.find(x=>x.id===id)).filter(Boolean);
 return b30head("biz30")+`<div class="sec" style="padding-top:12px"><div class="stat"><div><b class="num">30년</b><span>조사 기간 1996~2026</span></div><div><b class="num">92</b><span>실행한 검색어</span></div><div><b class="num">198</b><span>후보 주소(중복·오탐 포함)</span></div><div><b class="num">${b30n()}</b><span>공개 표시 항목, 근거 확인 ${b30ok()}</span></div></div>
 <h2 class="h2" style="margin-top:24px">핵심 결론</h2><div class="b30grid c3">
 <div class="card"><h3>사업은 행사·후원에 한정되지 않습니다</h3><p class="mut small" style="margin:6px 0 0">상품·서비스 제휴, 지역 작업장·생산·시설 운영, 장학·멘토링, 의료·문화 접근 지원까지 서로 다른 사업 모델이 공개자료에서 확인됩니다.</p></div>
 <div class="card"><h3>중앙회 발표가 전국 실행은 아닙니다</h3><p class="mut small" style="margin:6px 0 0">같은 보도를 여러 매체가 다시 실은 것을 새 제휴로 세지 않았고, 협약 발표와 실제 운영 기록을 구분했습니다.</p></div>
 <div class="card"><h3>실적은 체결 건수가 아니라 실제 제공으로</h3><p class="mut small" style="margin:6px 0 0">참여 지부, 수혜자, 수입·비용, 계약 유지기간 같은 자료가 있어야 사업 성과를 판단할 수 있습니다.</p></div></div>
 <h2 class="h2" style="margin-top:24px">사업 유형별 분포</h2><div class="card">${catBars()}<p class="small mut" style="margin:12px 0 0">공개 표시 ${b30n()}개 항목을 사업 성격으로 나눈 것입니다. 유형을 누르면 <a href="#biz30-types">사업 유형</a>에서 사례를 볼 수 있습니다.</p></div>
 <h2 class="h2" style="margin-top:24px">대표 사례</h2><div class="b30grid c3">${feat.map(caseCard).join("")}</div><p style="margin:14px 0 0"><a class="btn sm line" href="#biz30-cases">사례 전체 찾아보기</a></p>
 <h2 class="h2" style="margin-top:24px">이렇게 읽어 주세요</h2><div class="card"><ul class="rules"><li>협약 발표, 예산 편성, 실제 운영, 결산·성과 확인은 서로 다른 단계로 구분했습니다.</li><li>공동 행사에 참석한 것은 업무제휴로 확정하지 않았습니다. 후원도 계약형 제휴와 분리했습니다.</li><li>계획과 예산을 집행액으로, 행사 전체 인원을 복지회 직접 수혜자로 바꾸지 않았습니다.</li><li>이름이 비슷한 다른 단체의 자료는 소속이 확인되기 전까지 제외했습니다.</li><li>항목마다 '실행 수준'과 '확인되지 않은 것'을 함께 적었습니다.</li></ul></div></div>`}
const AXES=[["회원 대상 상품·서비스","원격 솔루션 판매·마케팅, 상조서비스, 의료 할인","계약서, 실제 이용·판매량, 참여 지부, 대금 흐름"],["지역 생산·일자리","작업장 포장, 쓰레기봉투 생산, 재활용 처리, 취업 알선","위탁·납품 계약, 결산, 근로자 명부의 비식별 집계"],["시설·이동 지원","센터 운영, 보조기기 수리, 이동지원 연혁","운영기간, 수탁자, 이용건수, 보조금 정산"],["교육·장학·멘토링","사랑의끈, 학생·후원자 연결, 온라인 교육","장학금 지급, 수혜자 중복 제거, 실제 교육 제공"],["문화·체육","공연·전시 접근, 체육행사","기관별 제공 횟수와 참석·이용 인원"],["후원·지역 연대","쌀·김장·물품 기부, 기업·로타리 지원","수령증, 제공대상, 단순 행사참석과 직접 지원 구분"],["국제 협력","해외 기관 협약과 의료·물품 지원 논의","서명 당사자, 수출·배송·지원 완료 증빙"]];
function vB30Types(){return b30head("biz30-types")+`<div class="sec" style="padding-top:12px"><div class="two"><div class="card lift"><h3 style="margin-bottom:4px">공개자료에 나타난 일곱 가지 사업 축</h3>${AXES.map(a=>`<div class="axis"><b>${a[0]}</b><div><span class="k">공개자료에 나타난 형태</span><br>${a[1]}</div><div><span class="k">실적을 확인하려면 필요한 자료</span><br>${a[2]}</div></div>`).join("")}</div>
 <div class="stack"><div class="card lift"><h3 style="margin-bottom:10px">항목을 성격별로 나누면</h3>${B30CATS.map(c=>`<div class="row" style="justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line)"><b>${c}</b><span><span class="chip m">${b30cnt(c)}항목</span> <button class="btn sm line" data-act="b30cat" data-c="${c}">사례 보기</button></span></div>`).join("")}</div>
 <div class="card"><h3 style="margin-bottom:6px">분석</h3><p class="mut small" style="margin:0">사업의 성격이 지역마다 상당히 다르므로, 한 가지 제휴 모델을 전국에 그대로 적용하기는 어렵습니다. 지부별 인력, 시설, 수탁 경험, 기업 관계를 따로 살펴야 합니다. 검색된 자료가 한쪽으로 치우쳐 있어 시대별 사업 비중이 늘었는지 줄었는지는 단정할 수 없습니다.</p></div></div></div></div>`}
const b30match=x=>(B30F.c==="전체"||x.cat===B30F.c)&&(B30F.s==="전체"||x.sd===B30F.s)&&(B30F.v==="전체"||x.verdict===B30F.v)&&(!B30F.q||(x.party+x.what+x.org+x.type).includes(B30F.q));
function b30table(){const l=B30.filter(b30match);return l.length?`<table class="tbl"><thead><tr><th>조직·시점</th><th>상대기관·유형</th><th>확인된 내용</th><th>판정·출처</th></tr></thead><tbody>${l.map(x=>`<tr><td data-l="조직·시점"><b>${esc(x.org)}</b><br><span class="small mut">${esc(x.when)}</span></td><td data-l="상대기관·유형"><b>${esc(x.party)}</b><br><span class="chip m" style="margin-top:4px">${esc(x.type)}</span></td><td data-l="확인된 내용">${esc(x.what)}<div class="caseline">실행 수준: ${esc(x.level)} · 증거: ${esc(x.ev)}<br>확인되지 않은 것: ${esc(x.gap)}</div></td><td data-l="판정·출처">${verdictChip(x.verdict)}<br>${srcLink(x)}</td></tr>`).join("")}</tbody></table>`:`<p class="mut" style="margin:14px 0">조건에 맞는 항목이 없습니다. 조건을 바꿔 보세요.</p>`}function vB30Cases(){const sds=[...new Set(B30.map(x=>x.sd))].sort((a,b)=>a.localeCompare(b,"ko"));const op=(v,cur)=>`<option ${v===cur?"selected":""}>${v}</option>`;
 return b30head("biz30-cases")+`<div class="sec" style="padding-top:12px"><div class="card lift"><div class="toolbar"><select id="b30c" aria-label="사업 유형">${["전체",...B30CATS].map(v=>op(v,B30F.c)).join("")}</select><select id="b30s" aria-label="지역">${["전체",...sds].map(v=>op(v,B30F.s)).join("")}</select><select id="b30v" aria-label="판정">${["전체","자료근거 있음","후보","참석만"].map(v=>op(v,B30F.v)).join("")}</select><input id="b30q" type="search" placeholder="상대기관·내용 검색" value="${esc(B30F.q)}" aria-label="검색"></div><p class="small mut" id="b30cnt" style="margin:0 0 8px">${B30.filter(b30match).length}개 항목 표시 · 지역 '중앙'은 중앙회, '미확인'은 소속 조직을 특정하지 못한 항목입니다.</p><div class="tblwrap" id="b30t">${b30table()}</div></div></div>`}
function vB30Map(){const by={};B30.forEach(x=>by[x.sd]=(by[x.sd]||0)+1);const lvl=n=>!n?0:n<=1?1:n<=3?2:n<=7?3:4;let heat="";
 for(let y=1;y<=5;y++)for(let x=1;x<=4;x++){const t=SIDO.find(z=>z[1]===x&&z[2]===y);heat+=t?`<button class="h${lvl(by[t[0]]||0)}" data-act="b30sd" data-sd="${t[0]}" aria-label="${t[0]} ${by[t[0]]||0}항목. 누르면 사례 찾기로 이동">${t[0]}<span class="c num">${by[t[0]]||0}</span></button>`:`<button class="hx" tabindex="-1" aria-hidden="true"></button>`}
 const bins=[["~2005",y=>y<=2005],["2006~10",y=>y>=2006&&y<=2010],["2011~15",y=>y>=2011&&y<=2015],["2016~20",y=>y>=2016&&y<=2020],["2021~26",y=>y>=2021]],yd=bins.map(b=>B30.filter(x=>x.yr&&b[1](x.yr)).length),nu=B30.filter(x=>!x.yr).length;
 return b30head("biz30-map")+`<div class="sec" style="padding-top:12px"><div class="two"><div class="card lift"><h3 style="margin-bottom:4px">지역별 확인 항목</h3><p class="small mut" style="margin:0 0 10px">칸의 숫자는 이 조사에서 공개 표시된 항목 수입니다. 활동 규모가 아니라 <b>조사에서 단서를 찾은 범위</b>입니다. 칸을 누르면 그 지역의 사례를 봅니다.</p><div class="heat">${heat}</div><div class="legend2"><span><i style="background:var(--brand-soft)"></i>0</span><span><i style="background:var(--t1)"></i>1</span><span><i style="background:var(--t2)"></i>2~3</span><span><i style="background:var(--t3)"></i>4~7</span><span><i style="background:var(--t4)"></i>8 이상</span></div><p class="small mut" style="margin:10px 0 0">중앙회 ${by["중앙"]||0}항목 · 소속 조직 미확인 ${by["미확인"]||0}항목은 지도에 표시하지 않았습니다.</p></div>
 <div class="card lift"><h3 style="margin-bottom:4px">연도별 확인 항목</h3><p class="small mut" style="margin:0 0 8px">시점이 확인된 항목을 5년 단위로 묶었습니다. 연도 미상 ${nu}항목 제외. 자료가 많이 남은 시기가 사업이 많았던 시기와 같다고 볼 수는 없습니다.</p>${svgBars(bins.map(b=>b[0]),yd,"","연도별 확인 항목 막대 그래프")}</div></div></div>`}
const GAP_REG=[["서울","중앙회 자료 중심","서울시회·구별 지부 이력과 지역사업"],["부산","기업의 장기간 후원 연혁","지부별 협약 원문·연도별 실행"],["대구","달성군 시설 운영 기록","다른 구·군 및 수탁 갱신"],["인천","대장 편입 부족","행사·협약 후보의 정확한 조직 확인"],["광주","대장 편입 부족","시회·구별 기관·기업 제휴"],["대전","후원·체육행사","구별 사업, 상업 제휴와 수탁사업"],["울산","대장 편입 부족","조직 존재·명칭 이력부터 확인"],["세종","대장 편입 부족","설립 전 충남 지역과 명칭 변동 대조"],["경기","용인·안산·안양·부천·광명·의왕·군포·성남","나머지 시군, 1990년대 및 계약·결산"],["강원","속초·춘천·도회","다른 시군 및 이동지원 운영자 변동"],["충북","진천·도회 후보","청주 등 다른 시군, 후보의 실행증빙"],["충남","보령·서산","다른 시군 및 센터 수탁 갱신"],["전북","군산 감사 기록","다른 시군, 취업 외 사업"],["전남","광양·고흥","목포·여수 등 다른 시군, 후원 상대 확정"],["경북","대장 편입 부족","시군별 의회·신문·기업 자료"],["경남","거제 및 대학 협력 후보","다른 시군, 대학 계약 당사자 확정"],["제주","의료서비스 협약","나머지 사업 및 실제 이용실적"]];
const GAP_PER=[["1996-10~2000","시설 연혁·주차장 운영 후보 등 희박","당시 명부·지역지 지면·의회 기록"],["2001~2005","백과사전형 지역연혁 후보 위주","원사업계획·수탁 및 보조금 정산"],["2006~2010","병원 계약·지역후원·시설 기록 일부","계약 본문·연도별 갱신·동명이단체 확인"],["2011~2015","교육·후원·수탁·감사 자료 일부","계획 대비 실행·결산"],["2016~2020","작업장·멘토링·문화협약·행사 일부","지역 확대와 사건별 중복 제거"],["2021~2026-10","서비스협약·센터위탁·후원·국제논의 일부","유지·해지·참여 지부·성과"]];
const gapTbl=(h,rows)=>`<div class="tblwrap"><table class="tbl"><thead><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td data-l="${h[i]}">${i===0?"<b>"+esc(c)+"</b>":esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
function vB30Gaps(){return b30head("biz30-gaps")+`<div class="sec" style="padding-top:12px"><div class="card"><p style="margin:0">검색에서 찾지 못했다는 것은 사업이 없었다는 뜻이 아닙니다. 과거 전국 지부 명부를 구하지 못해, 아래는 전수조사율이 아니라 <b>현재까지 살펴본 범위</b>입니다.</p></div>
 <div class="two" style="margin-top:14px"><div class="card lift"><h3 style="margin-bottom:6px">지역별 살펴본 범위</h3>${gapTbl(["지역","지금까지 살펴본 범위","다음에 확인할 것"],GAP_REG)}</div>
 <div class="stack"><div class="card lift"><h3 style="margin-bottom:6px">기간별 자료 상태</h3>${gapTbl(["기간","자료 상태","우선 행동"],GAP_PER)}</div>
 <div class="card lift"><h3 style="margin-bottom:6px">먼저 원문을 다시 확인할 것</h3><ul class="rules"><li>포천병원 2013년 계약: 상대기관 단락 전체 대조</li><li>서산 2024년 10주년: 협약 상대와 체결 내용 특정</li><li>군포 옛 주차장 사업, 대학 제휴, 영인바이오: 날짜·당사자·사업 내용 확인</li><li>속초 여성지부 지원: 물품 종류와 지급 방향 확인</li><li>홈페이지 조직 명부: 현재 표시와 실제 활동 조직·과거 조직 구분</li></ul></div></div></div>
 <div class="card" style="margin-top:14px"><h3 style="margin-bottom:6px">아직 끝나지 않은 범위</h3><ul class="rules"><li>1990년대와 2000년대 초반 자료가 특히 부족합니다.</li><li>과거 전체 지회·지부 명부와 명칭 변경·통폐합 이력을 확보하지 못해 검색의 기준 모수가 정해지지 않았습니다.</li><li>현재 홈페이지의 조직 수나 기사 속 홍보 수치를 30년 전체 또는 현재 활성 조직 수로 쓰지 않았습니다.</li><li>국내 언론 아카이브 전체, 유료 기사 원문, 지역신문 과거 지면, 비공개 협약서·결산은 대조하지 못했습니다.</li><li>그래서 수백·수천 건의 업무제휴가 있다거나 없다는 결론을 내리지 않았습니다.</li></ul></div></div>`}
function vB30Data(){return b30head("biz30-data")+`<div class="sec" style="padding-top:12px"><div class="two"><div class="stack"><div class="card lift"><h3 style="margin-bottom:8px">조사 방법</h3><ol class="rules"><li>뉴스, 기업 연혁·보도자료, 지자체·병원·의회 자료를 대상으로 검색어 92개를 실행했습니다.</li><li>후보 주소 198개를 모았고, 그중 근거를 검토한 항목이 51개입니다.</li><li>51개 중 ${b30n()}개를 공개 표시했습니다. 1개는 개인 후원자 이름이 들어 있어, 1개는 원문 전체를 아직 대조하지 못해 표시에서 뺐습니다.</li><li>표시 항목의 판정: 자료 근거 있음 ${b30ok()}, 후보 ${B30.filter(x=>x.verdict==="후보").length}, 참석만 ${B30.filter(x=>x.verdict==="참석만").length}.</li></ol></div>
 <div class="card lift"><h3 style="margin-bottom:8px">근거의 무게</h3><p class="mut small" style="margin:0">외부 기관의 거래·행정 기록 &gt; 외부 행사 보도 &gt; 자체 게시 &gt; 등록 목적·계획 순으로 증명력이 높다고 보았습니다. 이는 자료의 증명력을 뜻하며 기관의 가치를 평가한 점수가 아닙니다.</p></div></div>
 <div class="stack"><div class="card lift"><h3 style="margin-bottom:8px">집계와 검증 규칙</h3><ol class="rules"><li>이름이 비슷한 다른 단체·협회 자료는 소속이 확인되기 전까지 제외합니다.</li><li>기사 게시일과 행사일을 분리합니다.</li><li>같은 보도자료를 여러 매체가 실은 것은 하나의 사건으로 보고 출처를 여러 개 연결합니다.</li><li>협약 발표, 예산 편성, 실제 운영, 결산·성과 확인을 별도 단계로 기록합니다.</li><li>공동 행사 참석은 업무제휴로 확정하지 않고, 후원은 계약형 제휴와 분리합니다.</li><li>다자 협약은 행사 수와 상대기관 수를 따로 셉니다.</li><li>계획·예산을 집행액으로, 행사 전체 인원을 직접 수혜자로 바꾸지 않습니다.</li></ol></div>
 <div class="card lift"><h3 style="margin-bottom:8px">자료 내려받기</h3><p class="mut small" style="margin:0 0 10px">공개 표시한 ${b30n()}개 항목을 표(CSV)로 받을 수 있습니다. 엑셀에서 바로 열립니다.</p><button class="btn sm" data-act="b30csv">표(CSV) 내려받기</button></div></div></div></div>`}
Object.assign(PROUTES,{"biz30":vB30,"biz30-types":vB30Types,"biz30-cases":vB30Cases,"biz30-map":vB30Map,"biz30-gaps":vB30Gaps,"biz30-data":vB30Data});
/* 메뉴·검색·빠른 이동·홈·슬라이드 연결 */
MENU[0].sub.splice(5,0,["30년 발자취·제휴 분석","biz30","NEW"]);
const _lc=leftCol;leftCol=function(r){return _lc(String(r).startsWith("biz30")?"biz30":r)};
const _ci=cmdItems;cmdItems=function(){const L=_ci();L.splice(3,0,{t:"30년 발자취·제휴 분석",k:"페이지",go:"biz30"},{t:"30년 분석 사례 찾기",k:"페이지",go:"biz30-cases"});return L};
SLIDES.push({tag:"30년 발자취",h:"지난 30년, 복지회는 <b>어떤 사업</b>을 해 왔을까요?",p:"공개된 기사와 공문서로 모은 사업·업무제휴 사례를 지역별로 찾아볼 수 있습니다.",b:["사례 찾아보기","biz30-cases"]});
const _home=PROUTES.home;PROUTES.home=function(){const h=_home();const mark='<section><div class="sech"><h2>우리 지부 활동';const add=`<section><div class="sech"><h2>30년 발자취·제휴 분석<em class="new">NEW</em></h2><a href="#biz30">분석 보기</a></div><div class="blk" style="padding:14px 18px 16px"><p style="margin:0 0 12px">공개된 기사·공문서 ${b30n()}개 항목으로 본 지난 30년의 사업과 업무제휴입니다. 지역과 유형별로 찾아볼 수 있습니다.</p>${catBars()}<p style="margin:14px 0 0"><a class="btn sm" href="#biz30-cases">사례 찾아보기</a> <a class="btn sm line" href="#biz30-gaps">조사 공백 보기</a></p></div></section>`;return h.includes(mark)?h.replace(mark,add+mark):h};
const _vs=PROUTES.search;PROUTES.search=function(){const h=_vs(),q=SQ.toLowerCase();if(!q)return h;const hit=B30.filter(x=>(x.party+x.what+x.org+x.type).toLowerCase().includes(q));if(!hit.length)return h;
 const ex=`<div class="card" style="margin-top:12px"><h3>30년 발자취·제휴 분석 ${hit.length}건</h3><ul class="list">${hit.slice(0,8).map(x=>`<li><a href="#biz30-cases" data-act="b30q" data-q="${esc(x.party)}">${esc(x.party)}</a><span class="src">${esc(x.org)} · ${esc(x.when)}</span></li>`).join("")}</ul></div>`;const i=h.lastIndexOf("</div>");return i<0?h+ex:h.slice(0,i)+ex+h.slice(i)};
/* 중앙 사무국 화면 */
MNAV_C.splice(MNAV_C.length-1,0,["c-biz","30년 분석","chart"]);
CROUTES["c-biz"]=()=>shell("c-biz","30년 사업·제휴 분석","코덱스 리아가 공개자료로 조사한 결과입니다. 공개 화면에서 지역·유형별로 사례를 찾아볼 수 있습니다.",
 `<div class="mk"><a href="#biz30-cases"><b class="num">${b30n()}</b><span>공개 표시 항목</span></a><a href="#biz30-cases"><b class="num">${b30ok()}</b><span>자료 근거 있음</span></a><div><b class="num">92</b><span>검색어</span></div><div><b class="num">198</b><span>후보 주소</span></div></div>
 <div class="two"><div class="card lift"><h3 style="margin-bottom:10px">사업 유형별 분포</h3>${catBars()}</div><div class="card lift"><h3 style="margin-bottom:10px">바로 가기</h3><div class="stack">${B30TABS.map(t=>`<a class="btn sm line" href="#${t[1]}" style="justify-self:start">${t[0]}</a>`).join("")}</div><p class="small mut" style="margin:12px 0 0">확인되지 않은 범위가 많은 중간 조사입니다. 외부에 인용할 때는 '조사 공백'을 함께 보여 주세요.</p></div></div>`);
/* 동작 */
document.addEventListener("click",e=>{const t=e.target.closest("[data-act]");if(!t)return;const A=t.dataset.act;
 if(A==="b30cat"){B30F={c:t.dataset.c,s:"전체",v:"전체",q:""};go("biz30-cases");return}
 if(A==="b30sd"){B30F={c:"전체",s:t.dataset.sd,v:"전체",q:""};go("biz30-cases");return}
 if(A==="b30q"){B30F={c:"전체",s:"전체",v:"전체",q:t.dataset.q};go("biz30-cases");return}
 if(A==="b30csv"){try{const H=["번호","조직","시도","시점","구분","분류","상대기관","확인된 내용","실행 수준","확인되지 않은 것","증거 수준","판정","출처 주소"],q=s=>'"'+String(s==null?"":s).replace(/"/g,'""')+'"';
  const csv="﻿"+[H.map(q).join(",")].concat(B30.map(x=>[x.id,x.org,x.sd,x.when,x.type,x.cat,x.party,x.what,x.level,x.gap,x.ev,x.verdict,x.url].map(q).join(","))).join("\r\n");
  const u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download="복지회_30년_사업제휴_공개표시항목.csv";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000);toast("표를 내려받았어요")}catch(err){toast("내려받지 못했어요. 브라우저 설정을 확인해 주세요")}return}});
function b30refresh(){const t=$("#b30t");if(!t)return;t.innerHTML=b30table();$("#b30cnt").textContent=B30.filter(b30match).length+"개 항목 표시 · 지역 '중앙'은 중앙회, '미확인'은 소속 조직을 특정하지 못한 항목입니다."}
document.addEventListener("change",e=>{const i=e.target.id;if(i==="b30c"){B30F.c=e.target.value;b30refresh()}else if(i==="b30s"){B30F.s=e.target.value;b30refresh()}else if(i==="b30v"){B30F.v=e.target.value;b30refresh()}});
document.addEventListener("input",e=>{if(e.target.id==="b30q"){B30F.q=e.target.value.trim();b30refresh()}});
